### PR TITLE
[BRD] Fix Iron Jaws Feature & some cleanup

### PR DESCRIPTION
**Pull request by Gakai**
* Fix unreachable `Apex Option` in Iron Jaws Feature
* Simplify and clean both Iron Jaws features, as they were convoluted and unnecessarily complex
* Some cleanup I spotted during refactoring

### CODE REVIEW

**Comment by edewen** [comment]
Due to a feature request, #86  I added songs as an option instead of forced. This will conflict with the st and aoegcd cleanup.

**Comment by zbee** [comment]
If you are inclined to help keep this PR conflict-free, an option may be to PR to this branch, @edewen, just figured I'd mention it.

**Comment by edewen** [comment]
As there is no responses from gakai. I really liked the dot management so i ported your cleanup and dot management/apex arrow fix to the other bard pr of mine to consolidate.

**Comment by zbee** [comment]
Closing to keep this moving in edewen's PR.

**Pull request closed without merging**
